import "./globals.css";
import ReduxProvider from "@/components/providers/ReduxProvider";

export const metadata = {
  title: "Pos System Restaurent",
  description: "Generated by Pos System Restaurent",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
